### ISSUE TITLE
An error in the implementation of DKT!!

### ISSUE THREAD

**Issue by leaveM** [bigdata-ustc/EduKTM#15]
## 🐛 Description
In DKT  of EduKTM,  the loss function is ```BCEWithLogitLoss()``` , but there is already a ``` sigmoid() ``` at the end of ```forward()```  of ```Net``` , So, shouldn’t it be ``` BCELoss() ```  here? 
When I replace ```BCEWithLogitLoss()``` with  ```BCELoss() ``` , the performance has been greatly improved. ( AUC on **2009_skill_builder_data_corrected** from ~0.75 to ~0.80)

This looks like a big mistake， does this mean that there are some problems with the experimental results of many papers?

**Comment by leaveM** [comment]
Thanks for your work！
By the way, in most papers, the performance of DKT is  only  ~0.75  on 2009_skill_builder_data_corrected ,  
what do you think of this phenomenon？ Can you give me some suggestions ？ I would appreciate it!

**Comment by tswsxk** [comment]
Error has been fixed in v0.0.9.
