### ISSUE TITLE
Data processing of LPKT

### ISSUE THREAD

**Issue by leaveM** [bigdata-ustc/EduKTM#18]
## Description
There is only code to preprocess data on ASSISTChallenge in EduKTM-LPKT.
I tried to imitate your code to process the data of ASSIST12 and Ednet, but the experimental results are far from the results in the paper.
Can other code for processing data be open sourced?

**Comment by shshen-closer** [comment]
Thank you for this question! We will add the code for processing data of ASSIST12 and Ednet soon after. 
Before that, I suggest that you should check your preprocessing code carefully. For example, if you sorted them by timestamp at the beginning? Or if your pre-processed data works well on other models?

**Comment by Upekkha1** [comment]
> Thank you for this question! We will add the code for processing data of ASSIST12 and Ednet soon after. Before that, I suggest that you should check your preprocessing code carefully. For example, if you sorted them by timestamp at the beginning? Or if your pre-processed data works well on other models?

I also encountered the same problem when processing the assist2012 dataset.
Can other code for processing data be open sourced?Thanks

**Comment by shshen-closer** [comment]
Please go to https://github.com/shshen-closer/LPKT_tensorflow_version

We give the tensorflow version of LPKT, using Assist2012
