### ISSUE TITLE
[Bug: AKT]

### ISSUE THREAD

**Issue by ghzhao78506** [bigdata-ustc/EduKTM#30]
## 🐛 Description
attention function in AKTNet.py has a padding error, which may cause data leakage. 

## What have you tried to solve it?
original:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/51900582/178720710-d89592a2-95e7-41c1-82fe-b748d9119dbb.png">

solution:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/51900582/178720192-fddf9b1f-2125-4d16-92db-12eca6ebc1a0.png">

## Environment
(Conda) Python3.8

## Additional Info
This bug won't cause any runtime error. It use students' response information in error.

**Comment by shshen-closer** [comment]
您好，来信已收到

**Comment by tswsxk** [comment]
Would you like perform a leakage test to verify your question as we have tested it without any useful findings.
