### ISSUE TITLE
The training module can't be found,do you delete the file?

### ISSUE THREAD

**Issue by shuxu-C** [bigdata-ustc/EduKTM#36]
## Description
(A clear and concise description of what the feature is.)
- If the proposal is about a new dataset, provide description of what the dataset is and 
attach the basic data analysis with it.
- If the proposal is about an API, provide mock examples if possible.

## References
- list reference and related literature
- list known implementations

**Comment by tswsxk** [comment]
Hi, there, please point out which script you are using. If possible, post the running log.

**Comment by shuxu-C** [comment]
![image](https://user-images.githubusercontent.com/84367588/232649315-67e5d70d-ded0-41bf-ae91-4b757ef77ad4.png)

**Comment by shshen-closer** [comment]
您好，来信已收到

**Comment by tswsxk** [comment]
`dkt.train` is the class method defined inner the `DKT`, you can find the code [here](https://github.com/bigdata-ustc/EduKTM/blob/main/EduKTM/DKT/DKT.py#L46). Btw, it is not a good idea to use github as a code reader, as it does not work well like `vscode` or `pycharm`, especially when you want to check the package reference or function definition.

**Comment by shshen-closer** [comment]
您好，来信已收到
